version: "3.9"

# Common template for ActiveMQ services below
x-common-activemq:
  &default-common-activemq
  image: kartoza/activemq-docker:2.21.0
  build: activemq-docker
  env_file:
    - ../.env
  restart: on-failure

# Common template for GeoServer services below
x-common-geoserver:
  &default-common-geoserver
  image: kartoza/geoserver:2.21.0
  volumes:
    - geoserver-cluster-data:/opt/geoserver/data_dir
  env_file:
    - ../.env
  restart: on-failure
  depends_on:
    db:
      condition: service_healthy
    broker1:
      condition: service_healthy
  healthcheck:
    test: curl --fail -s http://localhost:8080/ || exit 1
    interval: 1m30s
    timeout: 10s
    retries: 3

services:

  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - geo-db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - FORCE_SSL=FALSE
    restart: on-failure
    healthcheck:
      test: "pg_isready -d gis"

  broker1:
    << : *default-common-activemq
    environment:
      - JAVA_HOME=/opt/java/openjdk
      - HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - SSL_MODE=false
      - ACTIVEMQ_SERVER_URI=tcp://broker1:61616?maximumConnections=1000&wireFormat.maxFrameSize=104857600&jms.useAsyncSend=true&transport.daemon=true
      - ACTIVEMQ_SERVER_DISCOVERYURI=multicast://default
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: netstat -ltn | grep -c ":61616"
      interval: 30s
      timeout: 10s
      retries: 10

  broker2:
    << : *default-common-activemq
    environment:
      - JAVA_HOME=/opt/java/openjdk
      - HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - SSL_MODE=false
      - ACTIVEMQ_SERVER_URI=tcp://broker2:61616?maximumConnections=1000&wireFormat.maxFrameSize=104857600&jms.useAsyncSend=true&transport.daemon=true
      - ACTIVEMQ_SERVER_DISCOVERYURI=multicast://default
    depends_on:
      db:
        condition: service_healthy
      broker1:
        condition: service_healthy

  broker3:
    << : *default-common-activemq
    environment:
      - JAVA_HOME=/opt/java/openjdk
      - HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - SSL_MODE=false
      - ACTIVEMQ_SERVER_URI=tcp://broker3:61616?maximumConnections=1000&wireFormat.maxFrameSize=104857600&jms.useAsyncSend=true&transport.daemon=true
      - ACTIVEMQ_SERVER_DISCOVERYURI=multicast://default
    depends_on:
      db:
        condition: service_healthy
      broker1:
        condition: service_healthy

  master:
    << : *default-common-geoserver
    ports:
      - "8081:8080"
    environment:
      - CLUSTERING=true
      - CLUSTER_DURABILITY=true
      - DB_BACKEND=POSTGRES
      - HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - SSL_MODE=allow
      - BROKER_URL=failover:(tcp://broker1:61616,tcp://broker2:61616,tcp://broker3:61616)
      - READONLY=disabled
      - TOGGLE_MASTER=true
      - TOGGLE_SLAVE=false
      - EMBEDDED_BROKER=disabled
      - RANDOMSTRING=23bd87cfa327d47e
      - INSTANCE_STRING=ac3bcba2fa7d989678a01ef4facc4173010cd8b40d2e5f5a8d18d5f863ca976f

  node:
    << : *default-common-geoserver
    ports:
      - "8082:8080"
    environment:
      - CLUSTERING=true
      - CLUSTER_DURABILITY=true
      - DB_BACKEND=POSTGRES
      - HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - SSL_MODE=allow
      - BROKER_URL=failover:(tcp://broker1:61616,tcp://broker2:61616,tcp://broker3:61616)
      - READONLY=enabled
      - TOGGLE_MASTER=false
      - TOGGLE_SLAVE=true
      - EMBEDDED_BROKER=disabled
      - RANDOMSTRING=33bd87cfa327d47e
      - INSTANCE_STRING=bc3bcba2fa7d989678a01ef4facc4173010cd8b40d2e5f5a8d18d5f863ca976f

volumes:
   geoserver-cluster-data:
   geo-db-data:
